### ISSUE TITLE
Getting "Certificate misses intermediates" error when adding domain

### ISSUE THREAD

**Issue by austinbutler** [rolodato/gitlab-letsencrypt#1]
This seems quite simple, so not sure how I am messing it up.

Here's the output (with details scrubbed):

```
gitlab-le --email email@email.com  --domain domain.com --repository user/domain.gitlab.io
GitLab personal access token (https://gitlab.com/profile/personal_access_tokens): 
By using Let's Encrypt, you are agreeing to the TOS at https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf
Uploaded challenge file, waiting for it to be available at ...
Could not find challenge file. Retrying in 15s...
Could not find challenge file. Retrying in 30s...
Could not find challenge file. Retrying in 1m...
Could not find challenge file. Retrying in 2m...
Could not find challenge file. Retrying in 4m...
Could not find challenge file. Retrying in 8m...

Success! Go to ... and create/update a domain with the following settings:

Domain: domain.com

Certificate (PEM):
-----BEGIN CERTIFICATE-----
```

Then on Gitlab.com "new domain" page I copied and pasted from each and matched up the name (certificate, then key) and when clicking create I get "certificate misses intermediates," and it won't allow me to proceed.

**Comment by rolodato** [comment]
Could you share the certificate output? Thanks!

**Comment by austinbutler** [comment]
Is there any way to retrieve it after the fact? Or can I just try it again? This is my first exposure to LE.

**Comment by rolodato** [comment]
I don't think so. You should be able to try again, only restriction is [LE's rate limit](https://letsencrypt.org/docs/rate-limits/) (5 per week).

**Comment by austinbutler** [comment]
``` txt
Certificate (PEM):
-----BEGIN CERTIFICATE-----
MIIFAjCCA+qgAwIBAgISA4gM3lNgb1Q6hjFI9bkeUgIMMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xNjA4MDExOTU1MDBaFw0x
NjEwMzAxOTU1MDBaMBoxGDAWBgNVBAMTD2F1c3RpbmJ1dGxlci5tZTCCASIwDQYJ
KoZIhvcNAQEBBQADggEPADCCAQoCggEBAMcn3XqWMYExdYCEbfGm1a84bb611Ry4
n2aDg7ss+nmsUugBR7nS46xPJM0wSMOn6mVs1JdZBXWETrxNvJ7TQd5DHHIncAb5
UEnMawPSyrecGlknUkv/43GiLw9f29KHM4YjvVS5mJeC6BYFWbFSYkOcocaJ2VZW
E/tDoBKsl3omiskqlkAcBbKHISGmFeXsYhlc5RjVeDS2b6s4aVu56P0dqZDxJviI
VdTHIa/3A6q6rUi3weUdYBbWob6Qt+vzZf+XtvJQN4LTEiH+0Eta65FqMsMOLQs4
f66w57KPhd0VUdEW2Ed84srwGx6QdVDqZydaW44mneXWd8nIuxXVG2kCAwEAAaOC
AhAwggIMMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYB
BQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUv/qJdc5kap66f8do8K19lsBf
PyAwHwYDVR0jBBgwFoAUqEpqYwR93brm0Tm3pkVl7/Oo7KEwcAYIKwYBBQUHAQEE
ZDBiMC8GCCsGAQUFBzABhiNodHRwOi8vb2NzcC5pbnQteDMubGV0c2VuY3J5cHQu
b3JnLzAvBggrBgEFBQcwAoYjaHR0cDovL2NlcnQuaW50LXgzLmxldHNlbmNyeXB0
Lm9yZy8wGgYDVR0RBBMwEYIPYXVzdGluYnV0bGVyLm1lMIH+BgNVHSAEgfYwgfMw
CAYGZ4EMAQIBMIHmBgsrBgEEAYLfEwEBATCB1jAmBggrBgEFBQcCARYaaHR0cDov
L2Nwcy5sZXRzZW5jcnlwdC5vcmcwgasGCCsGAQUFBwICMIGeDIGbVGhpcyBDZXJ0
aWZpY2F0ZSBtYXkgb25seSBiZSByZWxpZWQgdXBvbiBieSBSZWx5aW5nIFBhcnRp
ZXMgYW5kIG9ubHkgaW4gYWNjb3JkYW5jZSB3aXRoIHRoZSBDZXJ0aWZpY2F0ZSBQ
b2xpY3kgZm91bmQgYXQgaHR0cHM6Ly9sZXRzZW5jcnlwdC5vcmcvcmVwb3NpdG9y
eS8wDQYJKoZIhvcNAQELBQADggEBAHG/CPxgWksycHs3naQdcTvI/eKbhkblP3Mq
swowQHz+4J3d94jkvVJBdpwCkgRXeHdxUTn8+S4J3Ror40I7FyqVujbwZdJOJ1wT
9XMiuBIKSP2Ad6o+CSNnGW+fXi3b5ZSRPMhn8s3VRdw3fZfI64QA6T/CX9r4m9ka
i3EpNl7QZrLIFXCwS8dggRb7kTU4td2okKeeCb4J9IET0l2EJ5tKZqunYbmVvZM+
0nYVctBk8DDXevThPkGuLz5ailuBdSKxyDY2ONXhac8R5fK7xvhA6p0YbAWzzYYf
4wqK3RDRDvFA6Z661Emd/swUwRZHaIqKH9BWaF2uXpLU+dcPRQg=
-----END CERTIFICATE-----
```

**Comment by austinbutler** [comment]
I also tried adding it again, same intermediates error.

**Comment by rolodato** [comment]
Hey, I haven't been able to find the root cause yet, but I'm still taking a look. Any luck on your end?

**Comment by edelans** [comment]
Same error here. So I fell back to thetraditionnal  'manual way' (`./letsencrypt-auto certonly -a manual -d mydomain.com` ).

And I just pasted the outputed `fullchain.pem` file, which worked straight away in gitlab. (for the record, the letsencrypt cli tools outputs 4 files in `/etc/letsencrypt/live/mydomain` : cert.pem, chain.pem, fullchain.pem and privkey.pem.)

I have the impression that gitlab-le outputs the chain.pem, instead of fullchain.pem (which is just the contactenation of chain.pem + \n + cert.pem ).

From what I read here https://github.com/Daplie/le-acme-core/tree/v1.x : 

```
// Registration
LeCore.getCertificate(options, cb)            // returns (err, pems={ privkey (key), cert, chain (ca) })
```

I guess you can easily output the chain too and do the concatenation.

**Comment by rolodato** [comment]
@edelans I think you've hit the nail on the head. I don't have much experience with Let's Encrypt so it's absolutely possible I've missed this. I'll review this and submit a fix in a few days, or if you're up for a PR that would be fantastic. Thanks!

**Comment by edelans** [comment]
@rolodato sorry I wanted to do you this favor but I don't have any experience with npm packages development (how do you test this ?) and ES6 (those arrow functions everywhere make me feel I don't know js at all =) ). I'll see if I can find a few more time to try this again but no guarantees !

**Comment by rolodato** [comment]
I don't have any tests set up, I've only been testing this manually. You can replace [this reference to `LeCore.productionServerUrl`](https://github.com/rolodato/gitlab-letsencrypt/blob/69f5bf2c3fefe73b7bb28f54692d44924f4deaae/lib.js#L9) with `LeCore.stagingServerUrl` to use Let's Encrypt staging servers (rate limits do not apply there, and no real certificates are issued).

The [full output from the underlying LE library is available here](https://github.com/rolodato/gitlab-letsencrypt/blob/69f5bf2c3fefe73b7bb28f54692d44924f4deaae/index.js#L59-L63), so if you need to modify the output that's where you would do it. I'm swamped the next few weeks so I really appreciate you looking into this.

I'm planning to eventually add automatic tests that do dry runs on the staging server, validate the returned certificates, etc.

**Comment by edelans** [comment]
OK @rolodato,  everything needed was in https://github.com/Daplie/le-acme-core/blob/v1.x/README.md =). 

I'm testing it on the production server right now, PR incoming ASAP ;)

**Comment by edelans** [comment]
;)
