### ISSUE TITLE
npm package doesn't match github

### ISSUE THREAD

**Issue by JustinAiken** [rolodato/gitlab-letsencrypt#10]
- Latest version here is 1.0
- NPM has [1.0.1](https://www.npmjs.com/package/gitlab-letsencrypt)
- NPM version (1.0.1) lacks the #5 fix
- NPM version seems to have extra code in `lib.js` around `certCache` and `certStore`

**Comment by JustinAiken** [comment]
This "cleaned up code": https://github.com/rolodato/gitlab-letsencrypt/commit/17122b2c595fcc3eb13dd668b7fa749fc6d8ef6f seems to be present in the current npm package 🤔

**Comment by rolodato** [comment]
The npm package is at `bb77f28c56fe74c7277343c8aec9d5cacf89e1a5`, there just hasn't been a release yet. You can check this by doing `npm install gitlab-letsencrypt` and checking `gitHead` in `node_modules/gitlab-letsencrypt/package.json`.

I'll release 1.0.2 which should be at `f916e51f8b6c13ce4510eccfdff8ca9cf17586ac` if nothing else changes. Thanks for pointing it out!

**Comment by rolodato** [comment]
Released and published to npm: https://github.com/rolodato/gitlab-letsencrypt/commit/478b8c4b8336ca6b5e7ea9b66c2677d676c53956. Thanks again!
