### ISSUE TITLE
Unable to create valid certificates for www and root domains separately

### ISSUE THREAD

**Issue by monoblaine** [rolodato/gitlab-letsencrypt#13]
I'm trying to make my Gitlab pages-powered web site accessible over https for both `www.example.com` and `example.com`. I've read somewhere that you pass the domain names you want the certificate be valid for to Let's Encrypt during the certificate creation process. However, `gitlab-le` asks for just one domain name.

Regardless of all these, I should be able to create two separate certificates using `gitlab-le` for `www.example.com` and `example.com` and create domains using these separate certificates in Gitlab Pages settings. This is exactly what I'm doing, but when I create `example.com` with the certificate issued for `example.com` and then create `www.example.com` with the other certificate, the certificate for `example.com` becomes invalid. Same is true for the opposite case: Create `example.com` first and then `www.example.com`; `example.com`'s certificate becomes invalid (It says *"This certificate is for `www.example.com`"*) What am I doing wrong? Hope it's something obvious. Thanks!

**Comment by rolodato** [comment]
This is happening because the certificates are being issued separately, and GitLab Pages only lets you configure a single certificate. They are not invalidating each other, they are just separate certificates.

We would need to modify `gitlab-le` to support passing multiple domains. Currently we are only passing one, as shown here: https://github.com/rolodato/gitlab-letsencrypt/blob/7030f7cffa9eb8d79bd24dcb58c643196f2e26fb/lib.js#L83

If you are up to it, I would very much appreciate a pull request. Thanks!

**Comment by monoblaine** [comment]
Thanks for the lead! I've modified the code and successfully created a certificate for multiple domains. Working on the PR right now.

**Comment by ilpianista** [comment]
@monoblaine any progress?

**Comment by monoblaine** [comment]
Sorry, I've been busy with so many other things :/ I hope that the PR will be ready tonight.

**Comment by monoblaine** [comment]
Well, I'm finished but something's weird. I'm uploading the challenge file, having it get validated, but the last step where we delete the challenge file fails. GitLab API returns random errors like `Could not update branch master. Please refresh and try again.` or `Branch diverged`. I'm gonna get some sleep now and try GitLab API v4 in the morning.

**Comment by monoblaine** [comment]
I've found the problem: If you have more than one domain to validate, `letiny-core` doesn't wait until the last call to `removeChallenge` is finished. It immediately uploads the next challenge file to GitLab and it results in those errors (Some sort of race condition, I guess).
