### ISSUE TITLE
path issue

### ISSUE THREAD

**Issue by tscanlin** [rolodato/gitlab-letsencrypt#24]
I'm getting a path issue which I think is because I'm using windows. The file that uploaded to gitlab is "D:\public\.well-known\acme-challenge\-zzSyFqFx0AUvUk30gi5xU6O7pbZIQW2DG_9ojo_IGQ" in the root directory. This appears to be caused by `path.resolve('/', options.path, key),`. When I switched back to `public/.well-known/acme-challenge/${key}` it worked.

I really love this project and find it a very useful time saver. Would you be able to fix windows support?

**Comment by rolodato** [comment]
@tscanlin I don't have a Windows machine to test now, but I've pushed an attempt at a fix at https://github.com/rolodato/gitlab-letsencrypt/commit/311f37e337813dd4217b238760490c3246b53782. Could you try it out?

**Comment by tscanlin** [comment]
Yep, that fixed it! Thanks for the quick response.

**Comment by rolodato** [comment]
You're welcome, thank you for reporting it! Released 2.1.3 with the fix.
