### ISSUE TITLE
Could not find challenge file

### ISSUE THREAD

**Issue by dangayle** [rolodato/gitlab-letsencrypt#25]
I'm trying to use this to issue a certificate for bathtubbomb.com, and everything seems to work as intended, but the script can't find the .well-known challenge file.

![screen shot 2017-08-10 at 11 09 17 pm](https://user-images.githubusercontent.com/129611/29202906-4381c8f8-7e21-11e7-83eb-3ef86e0dc5ea.png)

I tried a different way with a separate site a few days ago, and it appears that Gitlab pages don't like the .well-known directory.  Any suggestions?

**Comment by dangayle** [comment]
Figured it out. Nothing wrong with the code, it was an issue with `/public/` dir

**Comment by rolodato** [comment]
Glad to hear you solved it, @dangayle. If there's anything in the README or `--help` that would have made this easier to fix, please let me know.

**Comment by dangayle** [comment]
This bit in the help file is a little confusing, TBH:

```
  --path        Absolute path in your repository where challenge files will
be
                uploaded. Your .gitlab-ci.yml file must be configured to
serve
                the contents of this directory under
                http://YOUR_SITE/.well-known/acme-challenge
                        [string] [default:
"/public/.well-known/acme-challenge"]
```

Not sure if you have to create this directory or what. I eventually figured
it out, but it was confusing.

**Comment by alchemistsaint** [comment]
Hello, i have the same problem, i already tried the above solution but still no luck.

**Comment by rolodato** [comment]
@alchemistsaint Could you start from a bare GitLab repository and share the steps to reproduce this? Thanks!

**Comment by alchemistsaint** [comment]
@rolodato i follow the guide and i tried the above solution and the challenge is now located on  

> /public/ .well-known/acme-challenge/

i tried to manually created the folder but still i cant access 

> mysite.com/.well-known/acme-challenge/[string]

my site is a plain HTML only.
thanks

**Comment by rolodato** [comment]
@alchemistsaint If you can't manually access the challenge file URL, then this tool will never work. There's something wrong with your repo or GitLab pages settings, I'm not sure I can help you beyond that unfortunately.

**Comment by dangayle** [comment]
The way I figured it out:

You must create a /public/ directory and put all of your html into that directory. I originally had it like this:

```
index.html
/public/
```

But you need it to be like this:

```
/public/index.html
```

--

Dan Gayle
Newsroom Developer
The Spokesman-Review

**Comment by alchemistsaint** [comment]
thanks man @dangayle @rolodato. I already figured it out, thanks for the great tool.
