### ISSUE TITLE
new version of letiny-core v2.0.0

### ISSUE THREAD

**Issue by coolaj86** [rolodato/gitlab-letsencrypt#3]
Just a heads up: I've published a new version of [letiny-core](https://github.com/Daplie/letiny-core).

I've bumped the major version not because any major design change, but because there are small breaking changes that I didn't want to provide backwards compatibility for.

The main change affecting you is that all options that explicitly required a PEM, forge object, ursa object, or JWK now require a `keypair` object which looks like this (all keys are optional):

``` javascript
// NOTE: this is an *any*, not an *all*
// passing a PEM will continue to work, it just needs to be on the key privateKeyPem
{ privateKeyPem: '<<just a pem>>'
, publicKeyPem: '<<just a pem>>'
, privateKeyJwk: {}
, publicKeyJwk: {}
, _ursa: {}                 // internal api, do not rely on this key
, _ursaPublic: {}       // internal api, do not rely on this key
, _forge: {}                // internal api, do not rely on this key
, _forgePublic: {}      // internal api, do not rely on this key
}
```

Note that the object may be modified by the functions calling it (i.e. to cache the intermediate internal ursa and/or forge objects).

The biggest change is that all of the RSA functions have been move to [rsa-compat](https://github.com/Daplie/rsa-compat.js), which has allowed for more thorough testing and to solve problems related to mixed formats of ursa / forge / jwk / pem objects being passed around and improperly detected in the previous version.

If you haven't had any problems with the current version and your current code is well-tested then you probably don't need to switch. Otherwise I would recommend upgrading.

Feel free to ask any questions.

**Comment by rolodato** [comment]
Hi AJ, thanks for the heads up. For now I haven't found a need to upgrade, but eventually I might consider it. Also, I don't want to make any major non-bugfix changes since this tool might become redundant: https://gitlab.com/gitlab-org/gitlab-ee/issues/474

I'll leave this open issue as a reminder for later if needed.

**Comment by rolodato** [comment]
Haven't found a compelling reason to update, so I'll close this and reopen if needed. Thanks!
