### ISSUE TITLE
Not able to get it working

### ISSUE THREAD

**Issue by CalebKing3** [rolodato/gitlab-letsencrypt#31]
I am sure I am missing something but this is the command I run and I'm getting a 404 Project not found. Not sure what step I am missing
`gitlab-le --domain http://veganeats.recipes --email calebking3@gmail.com --repository calebking3.gitlab.io/VeganEatsLandingPage --token @#!@#ASDAD`

**Comment by rolodato** [comment]
The `repository` option should be your repository identifier, not your GitLab pages URL. For example, if your repository is located at https://gitlab.com/rolodato/rolodato.gitlab.io, then its identifier is `rolodato/rolodato.gitlab.io`.

Also, you should remove the `http://` prefix from your domain, as it's not necessary in the context of Let's Encrypt (or TLS certificates rather).

**Comment by rolodato** [comment]
Closing this, let me know if you've managed to fix it.
