### ISSUE TITLE
npm ERR! code ENOVERSIONS npm ERR! No valid versions available for le-acme-core

### ISSUE THREAD

**Issue by alchemistsaint** [rolodato/gitlab-letsencrypt#43]
node: v9.0.0
npm: 5.5.1
I cant install it to ubuntu, it shows;

npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for le-acme-core

A complete log of this run can be found in:
npm ERR!     /home/saint/.npm/_logs/2018-01-27T23_16_57_128Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'gitlab-letsencrypt' ]
2 info using npm@5.5.1
3 info using node@v9.0.0
4 verbose npm-session 6624e82d7fe719ae
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/gitlab-letsencrypt 427ms (from cache)
8 silly pacote tag manifest for gitlab-letsencrypt@latest fetched in 461ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule gitlab-letsencrypt@3.1.1 checking installable status
14 http fetch GET 200 https://registry.npmjs.org/rsa-compat 99ms (from cache)
15 http fetch GET 200 https://registry.npmjs.org/request-promise 101ms (from cache)
16 silly pacote version manifest for rsa-compat@1.2.7 fetched in 109ms
17 silly resolveWithNewModule rsa-compat@1.2.7 checking installable status
18 silly pacote version manifest for request-promise@4.2.1 fetched in 114ms
19 silly resolveWithNewModule request-promise@4.2.1 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/bluebird 137ms (from cache)
21 silly pacote version manifest for bluebird@3.5.0 fetched in 146ms
22 silly resolveWithNewModule bluebird@3.5.0 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/xtend 468ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/ms 473ms (from cache)
25 http fetch GET 304 https://registry.npmjs.org/node-forge 474ms (from cache)
26 silly pacote version manifest for xtend@4.0.1 fetched in 523ms
27 silly resolveWithNewModule xtend@4.0.1 checking installable status
28 silly pacote version manifest for ms@2.0.0 fetched in 529ms
29 silly resolveWithNewModule ms@2.0.0 checking installable status
30 silly pacote version manifest for node-forge@0.7.1 fetched in 530ms
31 silly resolveWithNewModule node-forge@0.7.1 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/yargs 530ms (from cache)
33 http fetch GET 304 https://registry.npmjs.org/request 536ms (from cache)
34 silly pacote version manifest for yargs@8.0.1 fetched in 539ms
35 silly resolveWithNewModule yargs@8.0.1 checking installable status
36 silly pacote version manifest for request@2.81.0 fetched in 543ms
37 silly resolveWithNewModule request@2.81.0 checking installable status
38 silly fetchPackageMetaData error for le-acme-core@git+https://github.com/rolodato/le-acme-core.git#semver:2.1.0 No valid versions available for le-acme-core
39 verbose type version
40 verbose stack le-acme-core: No valid versions available for le-acme-core
40 verbose stack     at pickManifest (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/npm-pick-manifest/index.js:19:11)
40 verbose stack     at git.revs.then.remoteRefs (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/git.js:136:7)
40 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
40 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
40 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
40 verbose stack     at Promise._fulfillPromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:668:14)
40 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:694:18)
40 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
40 verbose stack     at Promise._resolveCallback (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:432:57)
40 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:524:17)
40 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
40 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
40 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
40 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
40 verbose stack     at Promise._resolveCallback (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:432:57)
40 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:524:17)
41 verbose cwd /home/saint
42 verbose Linux 4.4.0-112-generic
43 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "gitlab-letsencrypt"
44 verbose node v9.0.0
45 verbose npm  v5.5.1
46 error code ENOVERSIONS
47 error No valid versions available for le-acme-core
48 verbose exit [ 1, true ]

**Comment by rolodato** [comment]
I managed to reproduce this only by downgrading to npm 5.5.1, seems that there was a bug installing dependencies directly from git repositories: https://github.com/npm/npm/issues/18434

Should be fixed by upgrading to npm 5.6.x.

**Comment by alchemistsaint** [comment]
@rolodato thanks for the quick response :)
