### ISSUE TITLE
exit without output, project not found.

### ISSUE THREAD

**Issue by davidlaym** [rolodato/gitlab-letsencrypt#6]
When I run the app with valid parameters, it exit with no error and exit code 0 without doing anything.

Investigating this issue in code, It's because I have more than 20 projects in GitLab and the project i'm trying to get to is below the fold of the paging. Yes, GitLab applies paging to the api responses. https://github.com/gitlabhq/gitlabhq/tree/master/doc/api#pagination-link-header

So, the project is not being found and no error is given.

I detected the error and I'm trying to fix it. I'll be submitting a PR soon

**Comment by rolodato** [comment]
@davidlaym Good find! Thanks for working on the PR, let me know if you need any help with it.

**Comment by rolodato** [comment]
Closed in #8.
